from __future__ import annotations

from ily2.lib.general import run
from ily2.lib.output import info, success


def _uuid(device: str, dry_run: bool = False) -> str:
    if dry_run:
        return f"UUID-OF-{device}"
    out = run(f"blkid -s UUID -o value {device}", dry_run=dry_run, check=False).output.strip()
    return out or device


def generate_fstab(partitions: dict, root_fs: str, target: str = "/mnt/gentoo", dry_run: bool = False) -> None:
    info("/etc/fstab oluşturuluyor...")

    lines = ["# Generated by ILY2", "# <fs>  <mountpoint>  <type>  <opts>  <dump>  <pass>"]

    root_uuid = _uuid(partitions["root"], dry_run)
    lines.append(f"UUID={root_uuid}  /  {root_fs}  noatime  0 1")

    if "efi" in partitions:
        efi_uuid = _uuid(partitions["efi"], dry_run)
        lines.append(f"UUID={efi_uuid}  /boot/efi  vfat  defaults,noatime  0 2")

    if "swap" in partitions:
        swap_uuid = _uuid(partitions["swap"], dry_run)
        lines.append(f"UUID={swap_uuid}  none  swap  sw  0 0")

    content = "\n".join(lines) + "\n"
    path = f"{target}/etc/fstab"
    if dry_run:
        info(f"[dry-run] {path}:\n{content}")
        return
    with open(path, "w") as f:
        f.write(content)
    success("fstab yazıldı.")
