from __future__ import annotations

import os

from ily2.lib.chroot import Chroot
from ily2.lib.output import info, success, warn

MAKE_CONF_TEMPLATE = """\
# Generated by ILY2 - https://github.com/archlinux/archinstall (ilham kaynağı)
COMMON_FLAGS="-O2 -pipe -march=native"
CFLAGS="${{COMMON_FLAGS}}"
CXXFLAGS="${{COMMON_FLAGS}}"
FCFLAGS="${{COMMON_FLAGS}}"
FFLAGS="${{COMMON_FLAGS}}"

MAKEOPTS="-j{jobs}"
EMERGE_DEFAULT_OPTS="--jobs={jobs} --load-average={jobs}"

ACCEPT_LICENSE="*"
ACCEPT_KEYWORDS="amd64"

USE=""

GRUB_PLATFORMS="{grub_platforms}"

L10N="{locale_short}"
LC_MESSAGES=C.UTF-8

GENTOO_MIRRORS="https://distfiles.gentoo.org"
"""


def write_make_conf(target: str, jobs: int, uefi: bool, locale_short: str = "en", dry_run: bool = False) -> None:
    info("/etc/portage/make.conf yazılıyor...")
    content = MAKE_CONF_TEMPLATE.format(
        jobs=jobs,
        grub_platforms="efi-64" if uefi else "pc",
        locale_short=locale_short,
    )
    path = os.path.join(target, "etc/portage/make.conf")
    if dry_run:
        info(f"[dry-run] {path} içeriği:\n{content}")
        return
    with open(path, "w") as f:
        f.write(content)
    success("make.conf yazıldı.")


def sync_portage(chroot: Chroot) -> None:
    """
    Syncs the Portage tree. Tries emerge-webrsync first (fast, snapshot-based,
    works even when rsync mirrors are flaky); falls back to `emerge --sync`
    (git/rsync based, works regardless of which sync method a given release
    ships with) so this keeps working across old and new Gentoo profiles.
    """
    info("Portage ağacı senkronize ediliyor (emerge-webrsync)... Bu biraz zaman alabilir.")
    result = chroot.run("emerge-webrsync", check=False)
    if not result:
        warn("emerge-webrsync başarısız oldu, 'emerge --sync' ile tekrar deneniyor...")
        chroot.run("emerge --sync --quiet")
    success("Portage ağacı güncel.")


def select_profile(chroot: Chroot, init_system: str, hardened: bool = False) -> None:
    """
    Picks the best-matching amd64 profile without hardcoding a profile
    version number (e.g. "17.1", "23.0"...) so this keeps working as Gentoo
    bumps its default profile over time. Preference order:
      1. matches the requested init system (systemd vs openrc/none)
      2. matches the requested hardened flag
      3. is not a "developer"/"selinux"/experimental profile
      4. otherwise: leave whatever is already the default alone
    """
    info("Uygun Portage profili aranıyor...")
    listing = chroot.run("eselect profile list", check=False).output

    candidates = []
    for line in listing.splitlines():
        line = line.strip()
        if "]" not in line or "default/linux/amd64" not in line:
            continue
        try:
            index = line.split("]")[0].strip("[")
            name = line.split("]", 1)[1].strip().split()[0]
        except IndexError:
            continue
        candidates.append((index, name))

    def matches(name: str) -> bool:
        wants_systemd = init_system == "systemd"
        if wants_systemd != ("systemd" in name):
            return False
        if hardened != ("hardened" in name):
            return False
        if "selinux" in name or "developer" in name:
            return False
        return True

    chosen = next(((i, n) for i, n in candidates if matches(n)), None)

    if chosen:
        index, name = chosen
        chroot.run(f"eselect profile set {index}")
        success(f"Profil ayarlandı: #{index} ({name})")
    else:
        warn("Uygun profil otomatik bulunamadı, varsayılan profil korunuyor. "
             "Kurulum sonrası `eselect profile list` ile elle seçebilirsiniz.")
